spring.application.name=ChatBot

# ========================
# SERVER
# ========================
server.port=8081

# ========================
# SUPABASE / POSTGRESQL
# ========================
# Reemplazá estos valores con los de tu proyecto en Supabase
# Los encontrás en: Project Settings -> Database -> Connection String
spring.datasource.url=jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:6543/postgres?user=postgres.rsucipnybeooqiwreuyh&password=${DB_PASSWORD}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# ========================
# IA - DEEPSEEK
# ========================
ia.api.url=https://api.deepseek.com/v1/chat/completions
ia.api.key=${API_KEY_DEEPSEEK}
ia.model=deepseek-v4-flash

# ========================
# CANCHAS - Complejo Deportivo
# ========================
canchas.horario.inicio=08:00
canchas.horario.fin=23:00
canchas.turno.duracion-minutos=60

# Ver payloads JSON en consola (solo desarrollo)
logging.level.org.example.chatbot.service.ChatService=DEBUG
logging.level.org.springframework.web.reactive.function.client=DEBUG
#debug=true
#logging.level.org.springframework=DEBUG
#logging.level.org.example.chatbot=DEBUG

# ========================
# TELEGRAM BOT
# ========================
# Creá tu bot con @BotFather en Telegram y pegá el token acá
telegram.bot.token=${API_KEY_BOT}
telegram.bot.username=${NOMBRE_BOT}
